apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fscont
        image: nginx:1.14.2
        ports:
        - containerPort: 80
